language: c
os: linux
arch:
- amd64
compiler: gcc

addons:
  apt:
    packages:
    - libjansson-dev
    - libssl-dev
    - gnutls-dev
    - check
    - lcov
    - doxygen
    - graphviz
    - valgrind

before_install:
- sudo pip install codecov

before_script:
- set -ev
- mkdir build
- cd build

after_script:
- make install DESTDIR=`pwd`/root
- find root -type f -ls

jobs:
  include:
    - name: "Focal"
      dist: focal
      script:
      - cmake -DWITH_GNUTLS=YES -DWITH_OPENSSL=YES ..
      - make check

    - name: "Jammy"
      dist: jammy
      script:
      - cmake -DWITH_GNUTLS=YES -DWITH_OPENSSL=YES ..
      - make check

    - name: "Coverage Build"
      dist: jammy
      script:
      - cmake -DWITH_GNUTLS=NO -DWITH_OPENSSL=YES -DENABLE_COVERAGE ..
      - make
      - ctest -T memcheck
      - make doxygen-doc
      - make package_source
      - make check-code-coverage
      - codecov
