sudo: required
dist: xenial
language: c

arch:
 - amd64
 - ppc64le
 - arm64
 
compiler:
  - gcc
addons:
  apt:
    packages:
    - libjansson-dev
    - check
    - libssl-dev
    - lcov
before_install:
  - sudo pip install codecov
script:
  - autoreconf -i && ./configure --enable-code-coverage && make check-code-coverage
after_success:
  - codecov
