language: c
dist: jammy
os:
- linux
arch:
- amd64
compiler:
- gcc

addons:
  apt:
    packages:
    - libjansson-dev
    - libssl-dev
    - gnutls-dev
    - check

jobs:
  include:
    - name: "Build with CMake"
      script:
      - set -e
      - mkdir -p build
      - cd build
      - cmake -DWITH_GNUTLS=1 -DWITH_OPENSSL=1 ..
      - make
      - make test

    - name: "Build with Autotools"
      script:
      - set -e
      - autoreconf -fi
      - mkdir -p build
      - cd build
      -  ../configure --with-openssl --with-gnutls
      - make
      - make check

    - name: "Unit Tests, Code Coverage, Memcheck"
      before_install:
      - sudo pip install codecov
      - sudo apt-get install valgrind lcov doxygen graphviz
      script:
      - set -e
      - autoreconf -fi
      - mkdir build
      - cd build
      - ../configure --with-openssl --without-gnutls --enable-code-coverage --enable-valgrind
      - make
      - make check-valgrind
      - make check-code-coverage
      after_success:
      - codecov

# TODO https://docs.travis-ci.com/user/deployment-v2/providers/pages/
# TODO https://docs.travis-ci.com/user/deployment-v2/providers/releases/
