language: c
dist: jammy
os: linux
arch:
- amd64
- arm64
compiler: gcc

addons:
  apt:
    packages:
    - libjansson-dev
    - libssl-dev
    - gnutls-dev
    - check
    - lcov
    - doxygen
    - graphviz
    - valgrind

env:
- BUILD=cmake
- BUILD=autoconf
- BUILD=complete

before_install:
- sudo pip install codecov

before_script:
- autoreconf -fi
- mkdir build
- cd build

script:
- set -e
- if [ "${BUILD}" = "cmake" ]; then
    cmake -DWITH_GNUTLS=YES -DWITH_OPENSSL=YES ..;
    make check;
  elsif [ "${BUILD}" = "autoconf" ]; then;
    ../configure --with-openssl --with-gnutls;
    make check;
  else;
    ./configure --with-openssl --without-gnutls --enable-code-coverage --enable-valgrind;
    make check-code-coverage;
    make check-valgrind;
    make doxygen-doc;
    make dist-bzip2;
  fi

jobs:
  exclude:
  - arch: arm64
    env: BUILD=complete

after_success:
- if [ "${BUILD}" = "complete" ]; then
    codecov;
  fi
