language: c
dist: jammy
os:
- linux
arch:
- amd64
compiler:
- gcc

.base_packages: &base_packages
- libjansson-dev
- libssl-dev
- gnutls-dev
- check
- lcov

addons:
  apt:
    packages:
    - *base_packages

.common_make: &common_make
- make check-code-coverage
- make doxygen-doc

.autoconf_start: &autoconf_start
- set -e
- autoreconf -fi
- mkdir build
- cd build
- ../configure ${CONF_ARGS}
- *common_make

.cmake_start: &cmake_start
- set -e
- mkdir -p build
- cd build
- cmake ${CMAKE_ARGS} ..
- *common_make

jobs:
  include:
    - name: "Build with CMake"
      env:
      - CMAKE_ARGS="-DWITH_GNUTLS=YES -DWITH_OPENSSL=YES -DENABLE_COVERAGE=YES"
      script:
      - *cmake_start

    - name: "Build with Autotools"
      env:
      - CONF_ARGS="--with-openssl --with-gnutls --enable-code-coverage"
      script:
      - *autoconf_start

    - name: "Unit Tests, Code Coverage, Memcheck"
      addons:
        apt:
          packages:
          - *base_packages
          - valgrind
          - doxygen
          - graphviz
      before_install:
      - sudo pip install codecov
      env:
      - CONF_ARGS="--with-openssl --without-gnutls --enable-code-coverage --enable-valgrind"
      script:
      - *autoconf_start
      - make check-valgrind
      - make dist-bzip2
      after_success:
      - codecov

# TODO https://docs.travis-ci.com/user/deployment-v2/providers/pages/
# TODO https://docs.travis-ci.com/user/deployment-v2/providers/releases/
