language: c
dist: jammy
os:
- linux
arch:
- amd64
compiler:
- gcc

addons:
  apt:
    packages:
    - libjansson-dev
    - libssl-dev
    - gnutls
    - check
    - valgrind

jobs:
  include:
    - name: "Build with CMake"
      script:
      - mkdir -p build
      - cd build
      - cmake -DWITH_GNUTLS=1 -DWITH_OPENSSL=1 ..
      - make

    - name: "Build with Autotools"
      script:
      - autoreconf -fi
      - mkdir build
      - cd build
      -  ../configure --with-openssl --with-gnutls
      - make

    - name: "Unit Tests, Code Coverage, Memcheck"
      before_install:
      - sudo pip install codecov
      script:
      - autoreconf -fi
      - mkdir build
      - cd build
      -  ../configure --with-openssl --enable-code-coverage --enable-valgrind
      - make
      - make check-valgrind
      - make check-code-coverage
