language: c
os: linux
arch:
- amd64
compiler: gcc

addons:
  apt:
    packages:
    - libjansson-dev
    - libssl-dev
    - gnutls-dev
    - check
    - lcov
    - doxygen
    - graphviz
    - valgrind

before_install:
- sudo pip install codecov

before_script:
- set -ev
- autoreconf --version
- autoreconf -fi
- mkdir build
- cd build

jobs:
  include:
    - name: "Autotools Build (focal)"
      env: BUILD=auto
      dist: focal
      script:
      - ../configure
      - make

    - name: "CMake Build"
      env: BUILD=cmake
      dist: jammy
      script:
      - cmake -DWITH_GNUTLS=YES -DWITH_OPENSSL=YES ..
      - make check

    - name: "Autotools Build"
      env: BUILD=auto
      dist: jammy
      script:
      - ../configure --with-openssl --with-gnutls
      - make check

    - name: "Coverage Build"
      env: BUILD=coverage
      dist: jammy
      script:
      - ../configure --without-gnutls --enable-code-coverage --enable-valgrind
      - make check-valgrind check-code-coverage
      - codecov
