language: c
dist: jammy
os: linux
arch:
- amd64
- arm64
compiler: gcc

addons:
  apt:
    packages:
    - libjansson-dev
    - libssl-dev
    - gnutls-dev
    - check
    - lcov
    - doxygen
    - graphviz
    - valgrind

env:
- CMD="cmake -DWITH_GNUTLS=YES -DWITH_OPENSSL=YES .."
- CMD="../configure --with-openssl --with-gnutls"
- CMD="../configure --without-gnutls --enable-code-coverage --enable-valgrind"

before_install:
- sudo pip install codecov

before_script:
- autoreconf -fi
- mkdir build
- cd build

script:
- set -e
- ${CMD}
- if [[ "${CMD}" =~ "coverage" ]]; then make check-code-coverage; else make check; fi
- if [[ "${CMD}" =~ "valgrind" ]]; then make check-valgrind; fi
- if [[ "${CMD}" =~ "coverage" ]]; then make doxygen-doc; fi
- if [[ "${CMD}" =~ "coverage" ]]; then make dist-bzip2; fi

jobs:
  exclude:
  - arch: arm64
    env: CMD="../configure --without-gnutls --enable-code-coverage --enable-valgrind"

after_success:
- if [[ "${CMD}" =~ "coverage" ]]; then codecov; fi
