name: LibJWT Unit Tests, Coverage, and Docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ConorMacBride/install-package@v1
      with:
        brew: gnutls openssl@3 jansson pkgconf cmake check

    - name: Build, Test, and Docs
      uses: threeal/cmake-action@v2.1.0
      with:
        options: |
          WITH_OPENSSL=YES
          WITH_GNUTLS=YES
          WITH_TESTS=YES
        build-args: |
          --
          check

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ConorMacBride/install-package@v1
      with:
        apt: gnutls-dev libssl-dev libjansson-dev pkg-config check lcov valgrind

    - name: Build, Test, and Coverage
      uses: threeal/cmake-action@v2.1.0
      with:
        options: |
          ENABLE_COVERAGE=YES
        build-args: |
          --
          check
          check-code-coverage

    - uses: codecov/codecov-action@v5.1.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ${{github.workspace}}/build/check-code-coverage.info
        verbose: true

    - name: Memcheck
      working-directory: ${{github.workspace}}/build
      run: ctest -T memcheck
