name: Build and Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        brew: gnutls openssl@3 jansson pkgconf cmake doxygen graphviz

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make

    - name: Unit Tests
      working-directory: ${{github.workspace}}/build
      run: make check

    - name: Documents
      working-directory: ${{github.workspace}}/build
      run: make doxygen-doc

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ConorMacBride/install-package@v1
      with:
        apt: gnutls-dev libssl-dev libjansson-dev pkg-config check lcov valgrind

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -ENABLE_COVERAGE=YES

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make

    - name: Unit Tests
      working-directory: ${{github.workspace}}/build
      run: make check

    - name: Code Coverage
      working-directory: ${{github.workspace}}/build
      run: make check-code-coverage

    - uses: codecov/codecov-action@v5.1.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ${{github.workspace}}/build/check-code-coverage.info
        verbose: true

    - name: Memcheck
      working-directory: ${{github.workspace}}/build
      run: ctest -T memcheck
